// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  projectId: 'guardianroute-bxtii',
  appId: '1:557366290387:web:8ff26514e1108d2a2db126',
  storageBucket: 'guardianroute-bxtii.firebasestorage.app',
  apiKey: 'AIzaSyBhhj1mSwd1KFBW5lbzAwftv1ukRbWbG2I',
  authDomain: 'guardianroute-bxtii.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '557366290387',
  databaseURL: "https://guardianroute-ok4z5-default-rtdb.asia-southeast1.firebasedatabase.app"
};
